### ISSUE TITLE
Add sidebar active links highlight

### ISSUE THREAD

**Issue by cezarneaga** [gov-ithub/socent-frontend#25]
### Expected behavior
navigating to a route highlights the sidebar menu item. needs investigation whether react-router or material-ui provides active classes already. check material-ui lists.
### Actual behavior
no highlight present
### Steps to reproduce the problem.
navigate through routes
### Specifications
version of the project:  
operating system:  
npm version:  
node version:

**Comment by lzrmihnea** [comment]
To use for tests: https://facebook.github.io/jest/

**Comment by lzrmihnea** [comment]
Because the UI is empty, it is a little confusing at to which link should be highlighted. 
There was a mock-up document before, where the desired aspect of the UI was proposed. 
Could that mock-up document or any other mock-up document be presented? 
This would help get a better feeling as to how the task desired behavior should look like.
@cezarneaga

**Comment by cezarneaga** [comment]
Ok. I didnt explain too much but since we use material-ui the library proposed the style. its just a matter of adding a `background-color: rgba(0, 0, 0, 0.2);` style to the active link.
The task should investigate if material-ui has a way already implemented or if not i would do it by passing router context location.pathname, verify if === to the path in the list item.

not sure if i answered the right question though.

**Comment by lzrmihnea** [comment]
Pull requested from fork with implementation of this task. Will further research flexbox and a way to stick the last 2 sidebar buttons to the bottom of the sidebar, without including these in a separate div.
